return {
  -- "akinsho/bufferline.nvim",
  -- keys = {
  --   {
  --     [[<M-1>]],
  --     function()
  --       local elements = require("bufferline").get_elements()
  --       for index, data in ipairs(elements) do
  --         print(index)
  --
  --         for key, value in pairs(data) do
  --           print("\t", key, value)
  --         end
  --       end
  --     end,
  --   },
  --   {
  --     [[<M-2>]],
  --     function()
  --       require("bufferline").go_to(1)
  --     end,
  --   },
  -- },
  -- opts = function(_, opts)
  --   opts.options.numbers = "ordinal"
  -- end,
}
